language: java

script:
  - mvn clean package -Dmaven.test.skip.exec
  - mvn test -Pjacoco
  - mvn test -Pjacoco -Powb

jdk:
    - oraclejdk7
    - openjdk7

notifications:
  email:
    recipients:
      - antonin.stefanutti@gmail.com

after_success:
  - mvn jacoco:report -pl lib
  - mvn -N coveralls:jacoco
